### ISSUE TITLE
BIG QUERY SCRIPT

### ISSUE THREAD

**Issue by dguimard** [googleapis/java-bigquery#1093]
Thanks for stopping by to let us know something could be better!
Dear Team,

Will it be possible to give to the community BIGQUERY scripting grammar??

Kind regards
david

**Comment by shollyman** [comment]
Based on your inquiry, I'm guessing you're trying to build up a parser that understands the scripting extensions?  This particular issue tracker is for the BigQuery java client library only.

Generally, for users interested in query parsing, we direct their attention to the [ZetaSQL](https://github.com/google/zetasql) project, which is open sourcing the related components for processing the SQL syntax that BigQuery and other products support.  If there's something missing from the functionality there, I'd file an [issue](https://github.com/google/zetasql/issues) against the ZetaSQL project.

If I've somehow misunderstood your request, I'll also callout the fact that the BigQuery service itself has an issue tracker, where you can review public issues and also file your own.  More information can be found in the BigQuery docs: https://cloud.google.com/bigquery/docs/getting-support#issuetracker

**Comment by dguimard** [comment]
Hello ,

Thank you very much for your answer, yes i am trying to parse BIGQUERY **SCRIPT** that does not follow exctaly sql standard and that is fine.I think that would be great to have the BNF, or whatever you are using because there is some good business cases that can be solved  by using it.

i will study your answer,
Kind regards
david

**Comment by shollyman** [comment]
Checked with someone more familiar with the scripting feature functionality, and they pointed the following out to me in ZetaSQL:  https://github.com/google/zetasql/blob/master/zetasql/parser/bison_parser.y#L7887

Given that, I think ZetaSQL is probably the right avenue for further exploration.

**Comment by stephaniewang526** [comment]
Closing. We can re-open if further questions come up.
