### ISSUE TITLE
Job ID in Bigquery insertAll API Java

### ISSUE THREAD

**Issue by architmmmec** [googleapis/java-bigquery#1147]
HI Team,

I am using streaming insert ALL Java API to insert data in Bigquery. I want to set the job id while insertion. Is it possible to do so? If yes how?

**Comment by stephaniewang526** [comment]
[This method](https://cloud.google.com/bigquery/docs/reference/rest/v2/tabledata/insertAll) allows you to stream data into BigQuery one record at a time without a load job so it is not possible to set a jobId.

**Comment by stephaniewang526** [comment]
Closing this ticket. We can reopen if there are more questions.
