### ISSUE TITLE
BigQuery: Cannot interrupt Job.waitFor()

### ISSUE THREAD

**Issue by milo2048** [googleapis/java-bigquery#1247]
#### Environment details

MacOS 10.15.7
Java 1.8.0_172
Google libraries:

- gax-1.63.0
- google-cloud-bigquery-1.128.0
- google-cloud-core-1.94.7

#### Steps to reproduce

1. Run a query job in a Thread (my example uses ExecutorService and Callable)
2. In your task, use Job.waitFor to wait on the job to finish.
2. Interrupt the thread while Job.waitFor is running.
3. See that Job.waitFor does not throw InterruptedException and in fact retries after the thread is interrupted.

#### Code example

See attached JUnit test.  I apologize for the mess, I was trying to ensure that timing was not an issue when reproducing the issue!

#### Stack trace
N/A

#### External references such as API reference guides
Behavior per the API docs is that we should see InterruptedException:  https://googleapis.dev/java/google-cloud-bigquery/latest/com/google/cloud/bigquery/Job.html#waitFor-com.google.cloud.RetryOption...-

[bigquerythreads.zip](https://github.com/googleapis/java-bigquery/files/6352423/bigquerythreads.zip)

**Comment by stephaniewang526** [comment]
This is expected behavior -- `InterruptedException` is being retried. I am not sure what the ask is here.

**Comment by milo2048** [comment]
The API docs say that if the thread is interrupted while waiting on the job, waitFor() will throw InterruptedException - that is the correct behavior.  InterruptedException should not be retried, but should be rethrown.

With the way this code works in the latest version, I cannot interrupt a waiting job.  Our users attempt to cancel queries and they cannot be cancelled.  

Furthermore the code consumes the thread's interrupted flag so that our code cannot detect that the user attempted to cancel the task.

If an admin attempts to shut our application down after a user has begun a long running process involving BigQuery, the app will not shut down because the interrupted flag has been consumed and the thread that used BigQuery will not terminate.

Finally, earlier versions of the SDK threw InterruptedException under these circumstances and we did not see these issues.

**Comment by prash-mi** [comment]
Starting to look into this, will get back with an update soon.

**Comment by prash-mi** [comment]
It appears that it is working as expected. Please find the following observations:

I used the following test code:
  ```
 void testInteruptCurrentThread() throws ExecutionException, InterruptedException {
        Callable c = new Callable<TableResult>() {
            @Override
            public TableResult call() throws InterruptedException {

                BigQuery bigquery = BigQueryOptions.getDefaultInstance().getService();
                String sql = "SELECT * FROM `<replace with a valid table>` LIMIT 10";
                final QueryJobConfiguration.Builder jobBuilder = QueryJobConfiguration.newBuilder(sql).setUseLegacySql(
                        false).setAllowLargeResults(true);
                final QueryJobConfiguration queryJobConfiguration = jobBuilder.build();

                // The location must be specified; other fields can be auto-detected.
                final JobId jobId = JobId.newBuilder().setLocation("US").build();
                final Job initialJob = bigquery.create(JobInfo.newBuilder(queryJobConfiguration).setJobId(jobId)
                        .build());
                return initialJob.waitFor().getQueryResults();
            }
        };

        Future f = executorService.submit(c);

        System.out.println("f.isCancelled(): "+ f.isCancelled());
        Thread. currentThread(). interrupt();

        System.out.println("f.isCancelled(): "+ f.isCancelled());
        if (!f.isCancelled()){
            TableResult tr =  (TableResult)f.get();
            System.out.println("tr.getTotalRows(): "+ tr.getTotalRows());
        }else {
            System.out.println("Task Interrupted!!");
        }

    }
```

It gives `InterruptedException`:

```
Exception in thread "main" java.lang.InterruptedException
	at java.base/java.util.concurrent.FutureTask.awaitDone(FutureTask.java:418)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:190)
	at localtest.BQTest3.testInteruptCurrentThread(BQTest3.java:87)
	at localtest.BQTest3.main(BQTest3.java:24)
```

I went through the code you shared. It appears that you are trying `future.cancel(true);` , which doesn't really interrupts the current thread.  
As per this doc, `InterruptedException` should be thrown "if **_the current thread gets interrupted_** while waiting for the job to complete", Which appears to be true.
