### ISSUE TITLE
Retry issues caused by dns resolution

### ISSUE THREAD

**Issue by mschaszberger** [googleapis/java-bigquery#1254]
**Is your feature request related to a problem? Please describe.**

Related to https://github.com/googleapis/gax-java/issues/1301

Configuring retrying exceptions, in case of an error during dns resolution on http GRPC API, and the exception does not seems to be retried. Google Extensions for java does not consider this to be a retry case (the api does not seem to allow retry under errors of this sort).

**Describe the solution you'd like**

Expectation is that the big-query client given that retry policy is configured, will retry any retry-able exception that means:
- 5xx api errors
- connection errors

We see that host resolution exceptions are not yet retried.

The way the BQ client is set up now does not support any type of exception retry. It only retries on error codes.

**Comment by stephaniewang526** [comment]
PR is merged. We can follow up with any customer feedback using the buganizer.
