### ISSUE TITLE
Retry is not working for a Bigquery exception

### ISSUE THREAD

**Issue by architmmmec** [googleapis/java-bigquery#1264]
Here is the sample code

 private Job getJob(BigQuery bigquery, QueryJobConfiguration queryConfig) throws InterruptedException {
        JobId jobId = JobId.of(UUID.randomUUID().toString());
        Job queryJob = bigquery.create(
                JobInfo.newBuilder(queryConfig).setJobId(jobId).build());

        // Wait for the query to complete.
        queryJob = queryJob.waitFor(
               // RetryOption.initialRetryDelay(Duration.ofSeconds(1)),
                //RetryOption.totalTimeout(Duration.ofMinutes(4)),
                RetryOption.maxAttempts(10));
        return queryJob;
    }

Can someone check?

**Comment by stephaniewang526** [comment]
Could you clarify what the issue is? What are the steps to reproduce and what is current vs. expected behavior?

**Comment by architmmmec** [comment]
Okay, So I am throwing BigqueryException from this code. I have set the retry options but it is not retrying. My expectation is It should print the error multiple times  ```private TableResult runQuery(String query, BigQuery bigquery)
            throws InterruptedException {
        QueryJobConfiguration dmlQueryConfig = QueryJobConfiguration.newBuilder(query).build();

        Job queryJob = getJob(bigquery, dmlQueryConfig);

        if (queryJob == null) {
            throw new BigQueryException(0, "Bigquery Exception");
        } else if (queryJob.getStatus().getError() != null) {
            // You can also look at queryJob.getStatus().getExecutionErrors() for all
            // errors, not just the latest one.
            throw new RuntimeException(queryJob.getStatus().getError().toString());
        }

        // Execute the query.
        return queryJob.getQueryResults();
    }

**Comment by architmmmec** [comment]
@stephaniewang526  Any update on this?

**Comment by stephaniewang526** [comment]
The retry in the snippet you provided is happening [here](https://github.com/googleapis/java-bigquery/blob/master/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Job.java#L330-L344).

As a best practice, we don't recommend you to create your own query jobId. Try [this way](https://github.com/googleapis/java-bigquery/blob/master/samples/snippets/src/main/java/com/example/bigquery/SimpleQuery.java#L41-L44) instead.

**Comment by stephaniewang526** [comment]
Please re-open the ticket if you have follow-up questions.
