### ISSUE TITLE
MaterializedViewDefinition with partitioning and clustering

### ISSUE THREAD

**Issue by jessicalu2016** [googleapis/java-bigquery#1300]
Hi guys,

is there a way to specify partitioning and clustering when creating a Materialized View? `MaterializedViewDefinition` doesn't seem to provide a way to do it.

Thanks,
Jessica

**Comment by stephaniewang526** [comment]
Hi, this feature is supported in v1.130.0. Please try it out and re-open the ticket/open a new ticket if there are other issues.

**Comment by jessicalu2016** [comment]
awesome, Thanks!
