### ISSUE TITLE
add support for ParquetOptions for load/external tables

### ISSUE THREAD

**Issue by shollyman** [googleapis/java-bigquery#1302]
This FR is to add support for some advanced Parquet options (list inference and enums) when loading data or defining an external table.

Additional information has been shared out of band with library maintainers.

**Comment by curiouserrr** [comment]
Second the request.  In particular, the enumAsString parquet option doesn't appear to be exposed in this library, though it is available from the BQ cli.  It would be very helpful to have it available here.

**Comment by danieldeleo** [comment]
+1 for adding [DecimalTargetType](https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#decimaltargettype) to [ExternalTableDefinition](https://github.com/googleapis/java-bigquery/blob/master/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/ExternalTableDefinition.java).
