### ISSUE TITLE
Best practice to send data to bigquery from multiple services

### ISSUE THREAD

**Issue by maselvaraj** [googleapis/java-bigquery#14]
Hi,

I have a use case where I have 1000s of micro services. And all these services will be generate some json data that needs to be stored in big query. If I have to call big query from individual service and store the data in BigQuery, what is the recommended way of doing? Should I use streaming insert or do a load job ? Max should be 100 services calling big query in parallel to send their json data.  

Thanks,
Mani

**Comment by stephaniewang526** [comment]
Hi, thank you for your question. However, this is not an issue with the Java library. We recommend you to reach out to support (http://cloud.google.com/support) if you would like individual guidance on product usage.

Thanks,
Stephanie
