### ISSUE TITLE
Enable fasterxml to read/write bigquery classes

### ISSUE THREAD

**Issue by chamini2** [googleapis/java-bigquery#1459]
We are using BigQuery from Temporal, a tool to schedule and run workflows, and it passes results and arguments over JSON, so it must be able to read and write these structures. As it happens, it is perfectly capable of converting to JSON with fasterxml, but it is then not capable of reading it back because the classes do not offer a NoArgs constructor:

```
io.temporal.common.converter.DataConverterException: 
  com.fasterxml.jackson.databind.exc.InvalidDefinitionException: 
  Cannot construct instance of `com.google.cloud.bigquery.Schema` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (byte[])"{"fields":[{"name":"bike_id","type":
{"constant":"INTEGER","equivalent":"INT64","standardType":"INT64"},"subFields":null,"mode":"NULLABLE","description":null,"policyTags":null},{"name":"start_date","type":{"constant":"DATE","equivalent":"DATE","standardType":"DATE"},"subFields":null,"mode":"NULLABLE","description":null,"policyTags":null},{"name":"trip_count_last_week","type":{"constant":"INTEGER","equivalent":"INT64","standardType":"INT64"},"subFields":null,"mode":"NULLABLE","description":null,"p"[truncated 199 bytes]; line: 1, column: 2]
```

I have considered copying the data I need to an internal class, but it feels like unnecessary work if everything we are missing is a NoArgs constructor (which can be private, fasterxml works OK with this).

*****

Another thing that would work is making public the `toPb` `fromPb` methods and I can just send those in params/returns.

**Comment by stephaniewang526** [comment]
Please feel free to submit a PR with NoArgs constructor and I will review it.

**Comment by chamini2** [comment]
OK, will do
