### ISSUE TITLE
lastModifiedTime is always null for all Tables in the dataset list client call

### ISSUE THREAD

**Issue by Rohit-Kaliki** [googleapis/java-bigquery#1543]
`lastModifiedTime` is always null for all Tables in the dataset list client call, please find the code sample attatched: 

    DatasetId datasetIdFQDN = DatasetId.of(projectId, datasetId);
    Dataset dataset = bigQuery.getDataset(datasetIdFQDN);

    Page<Table> tableList = dataset.list(BigQuery.TableListOption.pageSize(1000));
    tableList.getValues().forEach(table -> {
        // lastModifiedTime is always null
        Long lastModifiedTime = table.getLastModifiedTime();
    });

As a workaround we are using `bigQuery.getTable(tableId);` to get the lastModifiedTime. Is this behaviour expected?

**Comment by stephaniewang526** [comment]
I'm able to repro this. Checking with the backend team. (b/203444616)
