### ISSUE TITLE
Bigquery: expose requirePartitionFilter field in Table.

### ISSUE THREAD

**Issue by pmakani** [googleapis/java-bigquery#156]
- As of now requirePartitionFilter field available in TimePartitioning but there is an another 
  type of partition available which is RangePartitioning and it's already implemented. 
  so we will have to expose requirePartitionFilter at top level in the table. 
- The existing requirePartitionFilter field will be deprecated in TimePartitioning.

**Comment by stephaniewang526** [comment]
What is the motivation behind this? Could you elaborate more? Is this driven by a known issue or any ticket?
