### ISSUE TITLE
Add DELETE alternative to WRITE_TRUNCATE to handle Row Level Security rules on Table 

### ISSUE THREAD

**Issue by VictorD-Veolia** [googleapis/java-bigquery#1593]
**Is your feature request related to a problem? Please describe.**
In BigQuery, the `TRUNCATE` operation removes all rows from a Table. However, when Table have [RLS](https://cloud.google.com/bigquery/docs/row-level-security-intro) rules set up, the `TRUNCATE` operation also removes those rules. A way to `TRUNCATE` rows from a table without removing `RLS` rules (which I guess is the most common use-case), is to run `DELETE FROM [TABLE] WHERE TRUE`.  This is actually not possible using this library.

**Describe the solution you'd like**
When using `WRITE_TRUNCATE` disposition, I would like a way to choose whether the library will do a `TRUNCATE` query (default), or a `DELETE WHERE TRUE` query.

**Comment by stephaniewang526** [comment]
Thank you for your input. I will get back to you on this.

**Comment by stephaniewang526** [comment]
Hi, we have an internal ticket open for this feature and this will be addressed on the backend (no clear ETA atm). This will not be provided through the client library as a feature since the backend needs to respect RLS change.
