### ISSUE TITLE
Convert TableResult to a Json object

### ISSUE THREAD

**Issue by BiatBang** [googleapis/java-bigquery#1594]
Hi, currently I'm iterating the tableResult row by row. For each row, I select each column's value and give it a column name then add to a json object. I found this method takes pretty long when the result if complex and large. 

Is there a better way to do this? Is there any methods helping user quickly converting it? Thanks a lot.

**Comment by stephaniewang526** [comment]
Yes, if converting to JSON object is what you need to do then it would take some time. What's the reason you need to do this?

**Comment by stephaniewang526** [comment]
We don't have this support in the client library. Some post-processing would need to be done on your side.
