### ISSUE TITLE
Double quote to backtick

### ISSUE THREAD

**Issue by kokmike** [googleapis/java-bigquery#1605]
Hello, 

It seems that Bigquery use backtick for quoted identifier. Is there any option to convert double quote to backtick automatically ?

like mysql sql_mode ANSI_QUOTES

**Comment by stephaniewang526** [comment]
The Java client library is pass-through for SQL queries so this is not supported as a feature.

**Comment by kokmike** [comment]
have you any suggestion if it is possible to use double quote instead of backtick in bigquery? Thanks
