### ISSUE TITLE
docs in package-info need a refresh

### ISSUE THREAD

**Issue by tswast** [googleapis/java-bigquery#1643]
https://github.com/googleapis/java-bigquery/blob/main/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/package-info.java

Since https://cloud.google.com/java/docs/reference/google-cloud-bigquery/latest/com.google.cloud.bigquery is where I landed when trying to understand the package from the API reference docs, `package-info` should get a refresh.

* [ ] Link to CreateTableAndLoadData.java 404s.
* [ ] Needs a link to BigQuery interface docs.
* [ ] Ideally link to main BigQuery docs, perhaps sample browser landing page for BigQuery?

**Comment by eaball35** [comment]
Fixing this in the repos will fix it in the docs. Changelogs are managed by [release-please](https://github.com/googleapis/release-please) and I believe that package-info page is generated by the [gapic-generator-java](https://github.com/googleapis/gapic-generator-java). It might make sense to move this issue to feature requests for those two pages.

**Comment by eaball35** [comment]
Moved issue to gapic-generator https://github.com/googleapis/gapic-generator-java/issues/992
