### ISSUE TITLE
com.google.api.services.bigquery.model.TableFieldSchema->com.google.cloud.bigquery.Field conversion issue

### ISSUE THREAD

**Issue by nbali** [googleapis/java-bigquery#1649]
#### Environment details

Library version(s): latest

#### Steps to reproduce

  1. Do anything that calls `com.google.cloud.bigquery.Field.fromPb(TableFieldSchema)` with a `TableFieldSchema` that has a `STRUCT` type.

#### Code example
```java
       System.out.println(LegacySQLTypeName.valueOf("STRUCT").equals(LegacySQLTypeName.RECORD)); // false
       System.out.println(LegacySQLTypeName.valueOf("RECORD").equals(LegacySQLTypeName.RECORD)); // true
```

#### Explanation
- According to the docs `com.google.api.services.bigquery.model.TableFieldSchema.type` can have the value `STRUCT`.
- Inside the mentioned `fromPb` this will be called `fieldBuilder.setType(LegacySQLTypeName.valueOf(fieldSchemaPb.getType()), subFields);`
- `LegacySQLTypeName.valueOf("STRUCT")` will return a newly created `LegacySQLTypeName` object as the originally registered one is registered with `RECORD`.
- So not this one:
```java
/** A record type with a nested schema. */
  public static final LegacySQLTypeName RECORD =
      type.createAndRegister("RECORD").setStandardType(StandardSQLTypeName.STRUCT);
```
- The `com.google.cloud.bigquery.Field.Builder.setType(LegacySQLTypeName, FieldList)` method that will be called with the returned `LegacySQLTypeName` contains a `LegacySQLTypeName.RECORD.equals(type)` check.
- That check will always fail, as `new LegacySQLTypeName("RECORD")` won't be equal with `new LegacySQLTypeName("STRUCT")`.

#### Stack trace
```
Caused by: java.lang.IllegalArgumentException: Only RECORD fields can have sub-fields
	at com.google.cloud.bigquery.Field$Builder.setType(Field.java:159)
	at com.google.cloud.bigquery.Field.fromPb(Field.java:361)
```

#### Any additional information below
Regarding a bigger picture, in my opinion every possible value in `TableFieldSchema` should act as equal objects, if they are just aliases.
For example:
```java
assertEquals(LegacySQLTypeName.valueOf("INTEGER"), LegacySQLTypeName.valueOf("INT64"));
assertEquals(LegacySQLTypeName.valueOf("FLOAT"), LegacySQLTypeName.valueOf("FLOAT64"));
assertEquals(LegacySQLTypeName.valueOf("BOOL"), LegacySQLTypeName.valueOf("BOOLEAN"));
assertEquals(LegacySQLTypeName.valueOf("RECORD"), LegacySQLTypeName.valueOf("STRUCT"));
```

**Comment by nbali** [comment]
(vaguely related to https://github.com/googleapis/google-cloud-java/issues/3942)

**Comment by stephaniewang526** [comment]
Hi, `com.google.cloud.bigquery.Field.fromPb(TableFieldSchema)` cannot be called outside the class since it's not a public method. Could you share what you're trying to accomplish (e.g. code snippet)?

Fundamental equality between`new LegacySQLTypeName("RECORD")` and `new LegacySQLTypeName("STRUCT")` is not possible since the backend will still send back RECORD any way. 

It would help if I know what problem you are trying to solve.

**Comment by nbali** [comment]
From `com.google.api.services.bigquery.model.TableFieldSchema.java`:
```java
  /**
   * [Required] The field data type. Possible values include STRING, BYTES, INTEGER, INT64 (same as
   * INTEGER), FLOAT, FLOAT64 (same as FLOAT), NUMERIC, BIGNUMERIC, BOOLEAN, BOOL (same as BOOLEAN),
   * TIMESTAMP, DATE, TIME, DATETIME, INTERVAL, RECORD (where RECORD indicates that the field
   * contains a nested schema) or STRUCT (same as RECORD).
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String type;
```

From documentation (https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#tablefieldschema)
```
type string

Required. The field data type. Possible values include:

STRING
BYTES
INTEGER (or INT64)
FLOAT (or FLOAT64)
BOOLEAN (or BOOL)
TIMESTAMP
DATE
TIME
DATETIME
GEOGRAPHY,
NUMERIC
BIGNUMERIC
RECORD (or STRUCT)

Use of RECORD/STRUT indicates that the field contains a nested schema.
```

IMO it doesn't matter what the backend sends back at the moment and/or what is the use-case that led to this report. According to the docs/specifications it might contain both STRUCT and RECORD (and INTEGER/INT64, BOOLEAN/BOOL, etc) and the library is unable to properly handle those.

**Comment by stephaniewang526** [comment]
Please feel free to raise a PR with proposed fix. We won't be able to get to this in some time.
