### ISSUE TITLE
com.google.api.services.bigquery.model.DatasetAccessEntry Java Client Bug

### ISSUE THREAD

**Issue by yongjiaw** [googleapis/java-bigquery#1717]
The `com.google.api.services.bigquery.model.DatasetAccessEntry.setTargetTypes` method does not work as expected.

Instead of using `new DatasetAccessEntry().setTargetTypes(util.Arrays.asList(new TargetTypes().setTargetType("VIEWS")))` as suggested by the signatures, I have to use `new DatasetAccessEntry().set("targetTypes", util.Arrays.asList("VIEWS"))`

I got this workaround after comparing the `GenericJson` objects added through the Bigquery UI.

The service expects `"targetTypes":["VIEWS"]`
But the client API produces `"target_types":[{"targetType":"VIEWS"}]`
    
This is possibly a more general API doc mistake than a java client bug.

**Comment by stephaniewang526** [comment]
Hi, this is an issue related to the BigQuery generated client (which comes from the JSON discovery doc). It's being worked on and will be fixed soon.
