### ISSUE TITLE
Issues with query Legacy SQL for Bigquery

### ISSUE THREAD

**Issue by vishakhaborse** [googleapis/java-bigquery#1722]
I want to query legacy SQL statement. I have datasets created in US, Mumbai and Delhi location. 
When i run standard SQL, the query runs successfully. However, when i prepend the SQL statement with #legacySQL or add Legacy SQL from the query settings , I get error as mentioned below:

1. If I provide a fully qualified name in the SQL statement (eg: Select * from `flogo-connectors.exploreTest.Student`), I face error
**Invalid table name: `flogo-connectors.exploreTest.Student` [Try using standard SQL (https://cloud.google.com/bigquery)**

2. If I provide name with only dataset and tablename in the SQL statement (eg: Select * from `exploreTest.Student`), I face error
**Not found: Dataset flogo-connectors:`exploreTest was not found in location US** , whereas the dataset is created in the US location only.

Tried with 3 different locations but same issue persists. I want to understand if there is any prerequisites or additional settings required for legacy SQL apart from changing in the Query settings or prepending #legacySQL before SQL statement.
Also how do we query legacy SQL statements.

**Comment by stephaniewang526** [comment]
You should be able to query with legacySQL. There is a `useLegacySQL` property you can set on `QueryJobConfiguration` just to be sure. Please try again.
