### ISSUE TITLE
ExtractStatistics does not have the `inputBytes` field

### ISSUE THREAD

**Issue by aekrylov** [googleapis/java-bigquery#1742]
As per [documentation](https://cloud.google.com/bigquery/docs/reference/rest/v2/Job#jobstatistics
), `inputBytes` field should be returned when calling `jobs.get` for an extract job, but the field is missing in the `ExtractStatistics` class.

`timeline` seems to be missing as well

#### Environment details

1. BigQuery: `jobs.get`
4. bigquery version(s): 2.4.1

#### Code example

```scala
bq.create(JobInfo.of(ExtractJobConfiguration
  .newBuilder(
    table.getTableId,
    "path"
  )
  .build()))
.waitFor()
```

#### External references such as API reference guides

- https://cloud.google.com/bigquery/docs/reference/rest/v2/Job#jobstatistics

**Comment by stephaniewang526** [comment]
Hi, please feel free to open a PR with this feature added and I will review it.
