### ISSUE TITLE
bug: use getType() instead of toString()

### ISSUE THREAD

**Issue by demondevilhades** [googleapis/java-bigquery#1761]
https://github.com/googleapis/java-bigquery/blob/fa998baa32437a5e39670c5c7399c0945de56d52/samples/snippets/src/main/java/com/example/bigquery/ExtractTableToJson.java#L46

#### Code example

FormatOptions.json().toString(); // FormatOptions{format=NEWLINE_DELIMITED_JSON}
FormatOptions.json().getType(); // NEWLINE_DELIMITED_JSON

So you should use getType() here instead of toString().

This is my first time I submit issue on Github. Please forgive me if I made mistake.

**Comment by stephaniewang526** [comment]
Please submit a PR for this fix. Make sure you initial commit is: "docs(samples): update ExtractTableToJson sample"

**Comment by demondevilhades** [comment]
Sorry. I made a mistake. It is right in main branch.

https://cloud.google.com/bigquery/docs/exporting-data#exporting_table_data
->
https://github.com/googleapis/java-bigquery/blob/fa998baa32437a5e39670c5c7399c0945de56d52/samples/snippets/src/main/java/com/example/bigquery/ExtractTableToCsv.java

This links from gcp page are not main branch. It makes me wrong.
