### ISSUE TITLE
BigQuery.listJobs is throwing NPE

### ISSUE THREAD

**Issue by shevek** [googleapis/java-bigquery#186]
Follow on from #17 (which still exists): listJobs is ALSO throwing NPE:

```
java.lang.NullPointerException: null
        at com.google.cloud.bigquery.JobStatistics.fromPb(JobStatistics.java:1183)
        at com.google.cloud.bigquery.JobInfo$BuilderImpl.<init>(JobInfo.java:154)
        at com.google.cloud.bigquery.Job.fromPb(Job.java:485)
        at com.google.cloud.bigquery.BigQueryImpl$32.apply(BigQueryImpl.java:1127)
        at com.google.cloud.bigquery.BigQueryImpl$32.apply(BigQueryImpl.java:1124)
        at com.google.common.collect.Iterators$6.transform(Iterators.java:783)
        at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
```

This is clearly dependent on the data the server is sending; in your tests you are not reproducing the server-side situation that we have; I don't know what that server side situation is, but I know it exists. In both this case and case #17, the client needs to be much more defensively programmed.

```
    JobConfiguration jobConfigPb = jobPb.getConfiguration(); // RETURNS NULL
    com.google.api.services.bigquery.model.JobStatistics statisticPb = jobPb.getStatistics();
    if (jobConfigPb.getLoad() != null) { // NPE
```

**Comment by shevek** [comment]
I'm going to take a wild guess here and say that listJobs can't handle jobs which were (a) dry-run, and (b) returned an error. Not totally sure. In any case, both this issue and #17 need some good client side defensive programming, because the situations ARE arising, and they are totally killing the API calls.

**Comment by pmakani** [comment]
@shevek can you please share your sample code which you have used, version of library and how we can reproduce this issue with steps.

**Comment by shevek** [comment]
It looks as if not having the listAllJobs permission is causing BQ server side to omit some critical fields, which might also cause this issue.

**Comment by shevek** [comment]
Try submitting a script job as user A, then listing jobs as user B who is not an admin and does not have the listAllJobs permission?

**Comment by stephaniewang526** [comment]
Closing this ticket as not enough information is provided for us to reproduce the issue. Please refer to https://cloud.google.com/bigquery/docs/managing-jobs for more information listing jobs. We will be adding more Java samples.

**Comment by shevek** [comment]
Whu?!
