### ISSUE TITLE
`getSchema().getFields()` behaves differently on `TableDefinition` vs `TableResult`

### ISSUE THREAD

**Issue by PlamenNeshkov** [googleapis/java-bigquery#1902]
#### Environment details

1. BigQuery
2. OS type and version: Ubuntu 21.10
3. Java version: 11.0.4-tem
4.  version(s):
    - https://github.com/googleapis/java-bigquery/releases/tag/v2.9.3
 
#### Steps to reproduce

  1. Create a table with at least one parameterized `NUMERIC` or `BIGNUMERIC` field
  2. Using `TableDefinition.getSchema().getFields()`, parameterized fields contain correct precision and scale
  3. Using `TableResult.getSchema().getFields()`, parametrized fields contain `null` precision and `null` scale

#### Code example

```java
BigQuery bigQuery = null; // create a valid BigQuery instance
Table table = bigQuery.getTable(TableId.of("some-project", "some-dataset", "some-table"));

table.getDefinition()
    .getSchema()
    .getFields(); // correct precision and scale

String query = "SELECT parameterized-column FROM some-table";
bigQuery.create(JobInfo.newBuilder(QueryJobConfiguration.newBuilder(query).build()).build())
    .waitFor()
    .getQueryResults()
    .getSchema()
    .getFields(); // null precision and scale
```

**Comment by prash-mi** [comment]
I was able to reproduce this, the library doesn't get these attributes from the backend in the second case. I am further checking with the backend team and will get back on this. Thanks.

**Comment by prash-mi** [comment]
Basically the API behaviour in the second implementations is expected. Source table schema properties are not propagated by queries, so you may want to use `getDefinition` to retrieve the required properties. 
Closing this issue as no fix is required in the client lib.

**Comment by PlamenNeshkov** [comment]
@prash-mi Is this expected behavior documented anywhere?
