### ISSUE TITLE
ITBiqueryTest.testConnectionCancel failing with AssertionError on Kokoro GraalVM job

### ISSUE THREAD

**Issue by mpeddada1** [googleapis/java-bigquery#1916]
The `ITBigqueryTest.testConnectionCancel` is failing with the following error for the Native Image testing Kokoro job. This failure was first discovered in https://github.com/googleapis/java-bigquery/pull/1374.

```
[ERROR] testConnectionCancel  Time elapsed: 5.127 s  <<< FAILURE!
java.lang.AssertionError
	at com.google.cloud.bigquery.it.ITBigQueryTest.testConnectionCancel(ITBigQueryTest.java:2610)
```
Note that the failure occurs before the Native Image build step. 

However, running this test locally with `mvn test -Pnative` results in a successful build.

<img width="954" alt="Screen Shot 2022-03-10 at 12 16 21 PM" src="https://user-images.githubusercontent.com/66699525/157722443-96b4801b-d8f4-463c-9fcf-62266f5a5a68.png">

Creating this issue to keep track of similar errors in the future.

cc @stephaniewang526

**Comment by stephaniewang526** [comment]
Hi, any update on this?

**Comment by mpeddada1** [comment]
Hi @stephaniewang526, I've just double checked that this passes locally. We used to run into this error in #1374 before we even got to the Native Image build stage. The good news is that, with the latest run of the Kokoro Native Image presubmit, the test in question passed (which makes me think that the `AssertionError` was transient). However, it currently fails at the native image build stage with:

```
Error: Substition: com.google.api.client.googleapis.services.AbstractGoogleClientRequest$ApiClientVersion.toString() conflicts with previously registered: com.google.api.client.googleapis.services.AbstractGoogleClientRequest$ApiClientVersion.toString()
```

The solution for this will be to upgrade java-shared-config with a newer version of native-image-support-java https://github.com/googleapis/java-shared-config/pull/465

**Comment by stephaniewang526** [comment]
Thank you @mpeddada1 for the thorough investigation! Any idea on the ETA of the newer version of java-shared-config and what version we should watch out for?

**Comment by mpeddada1** [comment]
Thanks @stephaniewang526! Looks like you've already merged the version upgrade PR in: https://github.com/googleapis/java-bigquery/pull/2000. We can try rebasing the PR now.

**Comment by suztomo** [comment]
Memo

<img width="1001" alt="Screen Shot 2022-04-20 at 5 08 18 PM" src="https://user-images.githubusercontent.com/28604/164323301-d5530b1b-a117-4585-9fc8-41928ffb51ae.png">
