### ISSUE TITLE
com.google.cloud.bigquery.BigQueryException: java.lang.NoSuchMethodError: com.google.gson.JsonParser.parseString(Ljava/lang/String;)Lcom/google/gson/JsonElement;

### ISSUE THREAD

**Issue by maddyobrienjones** [googleapis/java-bigquery#1985]
Hi! I'm using these versions on a GCP dataproc cluster with the 2.0.36-debian10 image and java8/scala 2.12 along with a jar that I can't share but has no gson dependencies:
  "com.google.cloud" % "google-cloud-bigquery" % "2.10.7",
  "com.google.cloud" % "google-cloud-bigqueryconnection" % "2.2.2",
  "com.google.cloud.spark" %% "spark-bigquery-with-dependencies" % "0.24.2"

The query runs successfully, but it throws a BigQueryException after the query has already been written to the destination table. I think this might be an issue with parsing a JSON formatted API response, but I haven't been able to figure it out or find the original code where the exception is coming from. It must be a dependency issue but I've tried creating the jar with different versions of gson and haven't been able to stop the exception being thrown.

#### Code example

```scala
  def writeQuery(client: BigQuery, name: String, query: String): Unit = {
    try {
      // Identify the destination table
      val destinationTable = TableId.of(dataset, name)
      // Build the query job
      val queryConfig =
        QueryJobConfiguration
          .newBuilder(query)
          .setDestinationTable(destinationTable)
          .setWriteDisposition(WRITE_APPEND)
          .build

      // Execute the query.
      client.query(queryConfig)

      // The results are now saved in the destination table.
      System.out.println(s"$name query ran/wrote successfully")
    } catch {
      case e @ (_: BigQueryException | _: InterruptedException) =>
        System.out.println("Saved query did not run \n" + e.toString)
    }
  }
```

#### Stack trace
```
Saved query did not run                                                         
com.google.cloud.bigquery.BigQueryException: java.lang.NoSuchMethodError: com.google.gson.JsonParser.parseString(Ljava/lang/String;)Lcom/google/gson/JsonElement;
```

**Comment by stephaniewang526** [comment]
This does not seem to be related to the BigQuery Java client library. We are including `gson` as a [compile scope dependency](https://github.com/googleapis/java-bigquery/blob/main/google-cloud-bigquery/pom.xml#L84-L87).
