### ISSUE TITLE
BigQuery: Add support for struct query parameters

### ISSUE THREAD

**Issue by tswast** [googleapis/java-bigquery#203]
`QueryParameterValue` does not currently support STRUCT parameters.

https://github.com/GoogleCloudPlatform/google-cloud-java/blob/0f6a47e19cc51a8baa9e13d9f1bb8d23c105e00a/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/QueryParameterValue.java#L58

See the API docs: https://cloud.google.com/bigquery/querying-data#using_structs_in_parameterized_queries for how these work in the API and an example query.

**Comment by stephaniewang526** [comment]
This is needed in order for us to add Java sample for https://cloud.google.com/bigquery/docs/parameterized-queries#using_structs_in_parameterized_queries
