### ISSUE TITLE
Update QueryPagination.java code for better paginated iteration

### ISSUE THREAD

**Issue by AyushWalekar** [googleapis/java-bigquery#2073]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**Is your feature request related to a problem? Please describe.**
With regards to the [query pagination example](https://github.com/googleapis/java-bigquery/blob/master/samples/snippets/src/main/java/com/example/bigquery/QueryPagination.java), the existing example doesn't cover scenario to iterate through all next row page-by-page. And I couldn't find an example to do so anywhere else.

**Describe the solution you'd like**
An easier approach would be to iterate 1st page in the `result` and then loop through next pages while updating `result` object

**Describe alternatives you've considered**
I have tried using `iterateAll()`, but it fetches all rows at once, instead iteration should be page-by-page as defined query config pageSize.

**Comment by stephaniewang526** [comment]
PR merged, hence closing this issue.
