### ISSUE TITLE
How to run DML in BigQuery old version API

### ISSUE THREAD

**Issue by andynhuttran** [googleapis/java-bigquery#2079]
I am working with com.google.api.services.bigquery.BigQuery, this is an old version.
How can I execute the DML query (delete statement for more detail **delete from project.dataset.tablename where....**) from the API.

Thanks for your help.
I am using java 8 and google-api-services-bigquery-v2-rev355-1.22.0

**Comment by meredithslota** [comment]
This repo is for a different library. The library you are asking about is here: https://github.com/googleapis/google-api-java-client-services/tree/main/clients/google-api-services-bigquery/v2 — I recommend asking there! For using DML in this client library, this documentation page might help: https://cloud.google.com/bigquery/docs/updating-data (includes a Java code sample for updating tables that might be a useful guide).

**Comment by meredithslota** [comment]
(Side question: the library you are using was released in 2017, I think, and likely lacks many newer features and fixes ... can I ask why you are still using it? I know there are lots of reasons folks can't upgrade; just curious.)

**Comment by andynhuttran** [comment]
working on a legacy system, so I have no chance to upgrade it. Thank for your mentions
