### ISSUE TITLE
Slow response time for stream inserts on java 11 and higher

### ISSUE THREAD

**Issue by tomaszpaneksabre** [googleapis/java-bigquery#2156]
In our SpringBoot based application we are inserting to BigQuery payloads of different sizes. In our load test we mix a big ones (few hundred of kilobytes) and small ones (few kilobytes) and try to generate traffic around 100TPS.  On java 8 we can reach that traffic with average response time of 2-3 seconds. Moving to java 11 (tested also on 17 with similar effects) lowers throughput and response time grows significantly. 

Problem must be with http transport layer. Replacing the default one by apache http client partially fixes the problem. Results are much better and stable but still not that good like for java 8. 

Are there any simple to apply tuning option for default http client? I couldn't find that would work.

What about apache http client? It's deprecated and I assume no longer supported.

**Comment by prash-mi** [comment]
@tomaszpaneksabre - this is an interesting finding. Can you please share some more details for me to be able to try and replicate it, like which service you are using and any sample code? 
I will get back on tuning the default http client.

**Comment by tomaszpaneksabre** [comment]
I forked simple spring boot rest demo example https://github.com/spring-guides/gs-rest-service as  https://github.com/tomaszpaneksabre/gs-rest-service-bigquery and added few methods there and jmeter load test configuration https://github.com/spring-guides/gs-rest-service/commit/dab16fa53ffe54167168f88ad9cd1634c37bc2c0.

To test just go to *complete* subfolder and execute 

`clean install `

followed by 

`java -jar target/rest-service-complete-bigquery-0.0.1-SNAPSHOT.jar`

And use jmeter (5.x) to run included *complete/bigquery.jmx* load test. 

You will need BigQuery setup/project with *greeting* table defined as `id: integer, content: string` and adjust class `GreetingController` to use that project and dataset.

Run with java 8 first and look at Aggregate Report. Next switch to 11 and look at Average and Throughput columns. In first case you should reach about 100TP with 200ms response time. In second one you may not reach 40TPS  and response may be about  3 seconds.

The numbers I gave here are different compared to may original post but I prepared much simpler example now compared to project we work on.

Finally you can simply change in code transport to apache http client. Results will be better on java 11 but not as good like in java 8 with default transport.

**Comment by tomaszpaneksabre** [comment]
Seems the problem was with my network. I run my test application and jmeter script inside gcp cloud shell and I got similar results for java 8 and 11.  It's still not perfect that performance of http access to big query depends on java version but because of consistent results inside gcp it's acceptable.

Below, for reference results for java 8 and 11 respectively:

./jmeter -n -t bigquery.jmx -l testresults.jtl
Creating summariser 
Created the tree successfully using bigquery.jmx
Starting standalone test @ 2022 Jul 12 21:13:12 UTC (1657660392896)
Waiting for possible Shutdown/StopTestNow/HeapDump/ThreadDump message on port 4445
Warning: Nashorn engine is planned to be removed from a future JDK release
summary +   1343 in 00:00:17 =   81.3/s Avg:   124 Min:   111 Max:  1226 Err:     0 (0.00%) Active: 33 Started: 33 Finished: 0
summary +   3038 in 00:00:30 =  101.3/s Avg:   115 Min:   109 Max:   433 Err:     0 (0.00%) Active: 93 Started: 93 Finished: 0
summary =   4381 in 00:00:47 =   94.2/s Avg:   118 Min:   109 Max:  1226 Err:     0 (0.00%)
summary +   3015 in 00:00:30 =  100.5/s Avg:   113 Min:   109 Max:   562 Err:     0 (0.00%) Active: 100 Started: 100 Finished: 0
summary =   7396 in 00:01:17 =   96.7/s Avg:   116 Min:   109 Max:  1226 Err:     0 (0.00%)
summary +   3000 in 00:00:30 =  100.0/s Avg:   116 Min:   109 Max:   437 Err:     0 (0.00%) Active: 100 Started: 100 Finished: 0
summary =  10396 in 00:01:47 =   97.6/s Avg:   116 Min:   109 Max:  1226 Err:     0 (0.00%)
summary +   3000 in 00:00:30 =  100.0/s Avg:   113 Min:   109 Max:   776 Err:     0 (0.00%) Active: 100 Started: 100 Finished: 0
summary =  13396 in 00:02:17 =   98.1/s Avg:   115 Min:   109 Max:  1226 Err:     0 (0.00%)
summary +   3001 in 00:00:30 =  100.0/s Avg:   113 Min:   109 Max:   325 Err:     0 (0.00%) Active: 100 Started: 100 Finished: 0
summary =  16397 in 00:02:47 =   98.5/s Avg:   115 Min:   109 Max:  1226 Err:     0 (0.00%)
summary +   3000 in 00:00:30 =  100.0/s Avg:   114 Min:   109 Max:   357 Err:     0 (0.00%) Active: 100 Started: 100 Finished: 0
summary =  19397 in 00:03:17 =   98.7/s Avg:   115 Min:   109 Max:  1226 Err:     0 (0.00%)
summary +   2999 in 00:00:30 =  100.0/s Avg:   114 Min:   109 Max:   261 Err:     0 (0.00%) Active: 100 Started: 100 Finished: 0
summary =  22396 in 00:03:47 =   98.9/s Avg:   115 Min:   109 Max:  1226 Err:     0 (0.00%)
summary +   3001 in 00:00:30 =  100.0/s Avg:   114 Min:   109 Max:   515 Err:     0 (0.00%) Active: 100 Started: 100 Finished: 0
summary =  25397 in 00:04:17 =   99.0/s Avg:   115 Min:   109 Max:  1226 Err:     0 (0.00%)


./jmeter -n -t bigquery.jmx -l testresults.jtl
Creating summariser 
Created the tree successfully using bigquery.jmx
Starting standalone test @ 2022 Jul 12 21:05:02 UTC (1657659902580)
Waiting for possible Shutdown/StopTestNow/HeapDump/ThreadDump message on port 4445
Warning: Nashorn engine is planned to be removed from a future JDK release
summary +      1 in 00:00:02 =    0.6/s Avg:  1358 Min:  1358 Max:  1358 Err:     0 (0.00%) Active: 4 Started: 4 Finished: 0
summary +   2341 in 00:00:25 =   93.5/s Avg:   127 Min:   110 Max:   975 Err:     0 (0.00%) Active: 54 Started: 54 Finished: 0
summary =   2342 in 00:00:27 =   87.6/s Avg:   128 Min:   110 Max:  1358 Err:     0 (0.00%)
summary +   3045 in 00:00:30 =  101.5/s Avg:   118 Min:   109 Max:   672 Err:     0 (0.00%) Active: 100 Started: 100 Finished: 0
summary =   5387 in 00:00:57 =   94.9/s Avg:   122 Min:   109 Max:  1358 Err:     0 (0.00%)
summary +   3000 in 00:00:30 =  100.0/s Avg:   116 Min:   109 Max:   214 Err:     0 (0.00%) Active: 100 Started: 100 Finished: 0
summary =   8387 in 00:01:27 =   96.7/s Avg:   120 Min:   109 Max:  1358 Err:     0 (0.00%)
summary +   2999 in 00:00:30 =   99.9/s Avg:   117 Min:   109 Max:  2826 Err:     0 (0.00%) Active: 100 Started: 100 Finished: 0
summary =  11386 in 00:01:57 =   97.5/s Avg:   119 Min:   109 Max:  2826 Err:     0 (0.00%)
summary +   3000 in 00:00:30 =  100.1/s Avg:   116 Min:   109 Max:   213 Err:     0 (0.00%) Active: 100 Started: 100 Finished: 0
summary =  14386 in 00:02:27 =   98.0/s Avg:   119 Min:   109 Max:  2826 Err:     0 (0.00%)
summary +   3000 in 00:00:30 =  100.0/s Avg:   114 Min:   109 Max:   195 Err:     0 (0.00%) Active: 100 Started: 100 Finished: 0
summary =  17386 in 00:02:57 =   98.4/s Avg:   118 Min:   109 Max:  2826 Err:     0 (0.00%)
summary +   2998 in 00:00:30 =   99.9/s Avg:   116 Min:   109 Max:  1720 Err:     0 (0.00%) Active: 100 Started: 100 Finished: 0
summary =  20384 in 00:03:27 =   98.6/s Avg:   118 Min:   109 Max:  2826 Err:     0 (0.00%)
summary +   3000 in 00:00:30 =  100.0/s Avg:   114 Min:   109 Max:   244 Err:     0 (0.00%) Active: 100 Started: 100 Finished: 0
summary =  23384 in 00:03:57 =   98.8/s Avg:   117 Min:   109 Max:  2826 Err:     0 (0.00%)
summary +   3000 in 00:00:30 =  100.0/s Avg:   114 Min:   109 Max:   212 Err:     0 (0.00%) Active: 100 Started: 100 Finished: 0
summary =  26384 in 00:04:27 =   98.9/s Avg:   117 Min:   109 Max:  2826 Err:     0 (0.00%)
summary +   3000 in 00:00:30 =  100.0/s Avg:   114 Min:   109 Max:   192 Err:     0 (0.00%) Active: 100 Started: 100 Finished: 0
summary =  29384 in 00:04:57 =   99.0/s Avg:   116 Min:   109 Max:  2826 Err:     0 (0.00%)
summary +   3000 in 00:00:30 =  100.0/s Avg:   114 Min:   109 Max:   465 Err:     0 (0.00%) Active: 100 Started: 100 Finished: 0
summary =  32384 in 00:05:27 =   99.1/s Avg:   116 Min:   109 Max:  2826 Err:     0 (0.00%)
summary +   3000 in 00:00:30 =  100.0/s Avg:   114 Min:   109 Max:   953 Err:     0 (0.00%) Active: 100 Started: 100 Finished: 0
summary =  35384 in 00:05:57 =   99.2/s Avg:   116 Min:   109 Max:  2826 Err:     0 (0.00%)
summary +   3000 in 00:00:30 =  100.0/s Avg:   114 Min:   109 Max:   408 Err:     0 (0.00%) Active: 100 Started: 100 Finished: 0
summary =  38384 in 00:06:27 =   99.2/s Avg:   116 Min:   109 Max:  2826 Err:     0 (0.00%)
summary +   3000 in 00:00:30 =  100.0/s Avg:   116 Min:   108 Max:   876 Err:     0 (0.00%) Active: 100 Started: 100 Finished: 0
summary =  41384 in 00:06:57 =   99.3/s Avg:   116 Min:   108 Max:  2826 Err:     0 (0.00%)
summary +   3000 in 00:00:30 =  100.1/s Avg:   114 Min:   108 Max:   175 Err:     0 (0.00%) Active: 100 Started: 100 Finished: 0
summary =  44384 in 00:07:27 =   99.4/s Avg:   116 Min:   108 Max:  2826 Err:     0 (0.00%)

**Comment by prash-mi** [comment]
Is there a chance we can isolate the performance numbers for the bigquery call itself? As the round trip response time will be a factor of many more things!

**Comment by tomaszpaneksabre** [comment]
I tried that with simple System.out.println() displaying average of 1000 responses:

```
        long t1 = System.currentTimeMillis();
        InsertAllResponse response = bigQuery.insertAll(builder.build());
        long t2 = System.currentTimeMillis();
        sum = sum + (t2 - t1);
        count++;
        if (count == 1000) {
            System.out.println(sum/1000);
            sum = 0;
            count = 0;
        }
```
In both cases, i.e. running server on my laptop and on gcp cloud shell I got very similar results compared to what jmeter (run respectively on laptop or cloud shell) gave me.

**Comment by prash-mi** [comment]
Closing as results are consistent running the tests on GCP, there might have been many factors affecting the results on local env.
