### ISSUE TITLE
BigQuery: 404 table not found even when the table exists

### ISSUE THREAD

**Issue by hichmo** [googleapis/java-bigquery#2368]
#### Environment details

1. com.google.cloud google-cloud-bigquery
2. OS type and version: macOS 12.6
3. Java version: 17
4.  version(s): java bigquery 2.17.1

#### Actual Behavior
I am trying to insert data to BigQuery in a new table just after create this table.
Sometimes I get a 404 error. This error is already described for go client https://github.com/googleapis/google-cloud-go/issues/975

#### Expected behaviour

Rows inserted without error table not found

#### Steps to reproduce
  
  1.   Create a table
  then 
  2. Insert rows on this table

#### Code example

```java
      
// Create
var tableId = TableId.of(projectId, datasetName, tableName);
var tableDefinition =
          StandardTableDefinition.newBuilder()
              .setSchema(getSchema())
              .build();
var tableInfo = TableInfo.newBuilder(tableId, tableDefinition).build();
bigQuery.create(tableInfo);
      
// Insert even if I use the response of bigQuery.create(tableInfo) the error occurs
var tableId = TableId.of(projectId, datasetName, tableName);
InsertAllRequest insertRequest = getInsertRequest(tableId, rows);
InsertAllResponse response = bigQuery.insertAll(insertRequest);
    
```

#### Stack trace
```
com.google.cloud.bigquery.BigQueryException: Table 725617850993:my_dataset.my_table not found.
```

Thanks!

**Comment by hichmo** [comment]
Hi @Neenu1995 
I have also try adding a delay or retry, and the result was the same.

I have just try, with success,  another solution by using inserting data with query

**Comment by ismailsimsek** [comment]
@shollyman @Neenu1995 any chance to provide a utility method which will wait for the table, maybe with timeout option?

more detail explained here https://github.com/googleapis/google-cloud-go/issues/975#issuecomment-1503689334

**Comment by shollyman** [comment]
The client has no special awareness and no ability to navigate the inconsistencies, so this quickly degrades to some form of sleep.  That's better handled by the user code, where more state awareness of changes is likely.

Closing this issue.
