### ISSUE TITLE
Sync sample dependencies

### ISSUE THREAD

**Issue by elharo** [googleapis/java-bigquery#24]
The samples directory is behind the rest of the repo in dependency versions. Let's figure out how to share dependency versions between these.

**Comment by elharo** [comment]
change the samples/pom.xml to skip the deployment in the nexus staging and deploy plugin

**Comment by stephaniewang526** [comment]
Being addressed by @chingor13 : https://docs.google.com/document/d/11J83wQUDcDX7Q1o8W7Xj7PKXrvMZrxUlXQB2t-YsJ4U/edit?usp=sharing
