### ISSUE TITLE
HivePartitioningOptions does not have option to set require partition filter

### ISSUE THREAD

**Issue by hidarapaneni** [googleapis/java-bigquery#251]
in bigquery API i see four options mode,uriprefix,requirepartitionfilter & fields.. but in java client i just see two options(first 2).. not sure if this was intentional..

https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#hivepartitioningoptions

requirePartitionFilter (boolean)

enabling requirepartition filter out side of hivepartitionoptions throws out error ---> Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "message" : "require_partition_filter has been set for a hive-partitioned table without using the HivePartitioningOptions. To configure external, hive-partitioned tables -- including setting require_partition_filter -- please use the HivePartitioningOptions. Setting require_partition_filter on the top-level table definition, or via the TimePartitioning field, does not configure hive-partitioned tables.",
    "reason" : "invalid"
  } ],
  "message" : "require_partition_filter has been set for a hive-partitioned table without using the HivePartitioningOptions. To configure external, hive-partitioned tables -- including setting require_partition_filter -- please use the HivePartitioningOptions. Setting require_partition_filter on the top-level table definition, or via the TimePartitioning field, does not configure hive-partitioned tables.",
  "status" : "INVALID_ARGUMENT"
}

**Comment by stephaniewang526** [comment]
Looks like those two fields, 
``` "requirePartitionFilter": boolean,
  "fields": [
    string
  ]``` are missing from the discovery doc:
https://github.com/googleapis/discovery-artifact-manager/blob/b29cb224a4cbd792e9c8ec9525819608bed531c5/discoveries/bigquery.v2.json#L5265-L5277

we will discuss and follow up.

**Comment by hidarapaneni** [comment]
Is there any update on this.. just checking

**Comment by hidarapaneni** [comment]
It seems native table hive partitioning options API implementation is also implemented incorrectly.. Here is the code snippet. bq command works fine but API throws out error -->

BQ Cli --> 
`
bq load --source_format=PARQUET --time_partitioning_field month_end_date --time_partitioning_type DAY  --replace  --schema_update_option=ALLOW_FIELD_RELAXATION --require_partition_filter --hive_partitioning_mode=AUTO --hive_partitioning_source_uri_prefix=xxx <tablename> xxx/*
`

API --> 
`val TIME_PARTITIONING = TimePartitioning.newBuilder(TimePartitioning.Type.DAY)
          .setRequirePartitionFilter(true)
          .setField(partColumn)
          .build()
        baseConfig.setTimePartitioning(TIME_PARTITIONING)
        baseConfig.setHivePartitioningOptions(
          HivePartitioningOptions.newBuilder()
            .setMode("AUTO")
            .setSourceUriPrefix(path.replace("*",""))
            .build
        )`

Exception --> 
`java.io.IOException: BigQuery job JobId{project=xxxx, job=xxxx, location=US} failed with message: Incompatible table partitioning specification. Expects partitioning specification none, but input partitioning specification is interval(type:day,field:month_end_date)`

**Comment by stephaniewang526** [comment]
@shollyman

**Comment by shollyman** [comment]
Backend team is normally discovery document, which address the underlying issue of missing partition filter requirement.

**Comment by shollyman** [comment]
s/normally/normalizing/

**Comment by shollyman** [comment]
This should be available from discovery, modulo publishing latency on the java discovery clients.

**Comment by hidarapaneni** [comment]
Thanks @stephaniewang526  for fixing the require partition filter.. did we also fix the hive mode for native table option as well.. https://github.com/googleapis/java-bigquery/issues/251#issuecomment-667595463

**Comment by hidarapaneni** [comment]
I see even native table hive partitioning is also fixed.. its loading as expected..
