### ISSUE TITLE
Feature parity for storage related fields across REST API and Java SDK

### ISSUE THREAD

**Issue by sumeetgajjar** [googleapis/java-bigquery#2672]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**Is your feature request related to a problem? Please describe.**
The BigQuery REST API supports the followings fields in its response.
```javascript
{
  "numTimeTravelPhysicalBytes": "23083567",
  "numTotalLogicalBytes": "222712206",
  "numActiveLogicalBytes": "222712206",
  "numLongTermLogicalBytes": "0",
  "numTotalPhysicalBytes": "83798234",
  "numActivePhysicalBytes": "83798234",
  "numLongTermPhysicalBytes": "0"
}
```
However, the corresponding getters are not available in the JAVA client: [com.google.cloud.bigquery.Table](https://cloud.google.com/java/docs/reference/google-cloud-bigquery/latest/com.google.cloud.bigquery.Table#expandable-1)

**Describe the solution you'd like**
Add the above fields in `TableInfo` class of the JAVA client.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Neenu1995** [comment]
@sumeetgajjar , Thanks for looking into this.
There is a known issue between the type of casing of these fields and we have team working on fixing this at the root.
