### ISSUE TITLE
[WARNING] JAR will be empty - no content was marked for inclusion!

### ISSUE THREAD

**Issue by elharo** [googleapis/java-bigquery#27]
[WARNING] JAR will be empty - no content was marked for inclusion!
[INFO] Building jar: /home/elharo/java-bigquery/target/google-cloud-bigquery-parent-1.102.1-SNAPSHOT-tests.jar

**Comment by chingor13** [comment]
I originally thought this was because the parent was marked as a jar project and would be incorrectly released, but that is not the case.

**Comment by stephaniewang526** [comment]
Looks like this is a protobuf issue -- Protobuf doesn’t generate tests. Not sure if there's anything we can do here.

**Comment by elharo** [comment]
There should be some way we can prevent that from being generated. Not  a high priority though.

**Comment by stephaniewang526** [comment]
Closing per discussion during open source sync.
