### ISSUE TITLE
Without knowing which region I have datasets in, how do I list all datasets via a info schema query?

### ISSUE THREAD

**Issue by KarlHakanNordgren** [googleapis/java-bigquery#2745]
Hi

Without knowing which region I have datasets in, how do I list all datasets via a info schema query? If it is not possible, how can I get `listDatasets()` to return values -- it currently mainly returns nulls.

**Comment by KarlHakanNordgren** [comment]
For `listDatasets` the answer is probably [this](https://stackoverflow.com/questions/73156862/cant-get-list-of-all-dataset-with-information-schema-and-schemata-on-bigquery-p). Without knowing which region I have datasets in, how do I list all datasets (via a info schema query)?

**Comment by KarlHakanNordgren** [comment]
@Neenu1995 : Do you know who knows the answer to this one?

**Comment by Neenu1995** [comment]
Hi @KarlHakanNordgren,

To get dataset info from INFORMATION_SCHEMA, a region is required.

The recommended way to get a list of datasets is to use the listDatasets() method. Please follow this [sample](https://cloud.google.com/bigquery/docs/listing-datasets) for more details. 

If, after following the sample, the listDatasets() method still provides a null, please validate the following:

1. You have required permissions on the project to retrieve the list of datasets.
2. You are using the correct credentials.
3. There are datasets in the project to be retrieved.

Hope this helps. Closing the issue for now. Feel free to reopen if required.
