### ISSUE TITLE
Are multi region information schema queries possible?

### ISSUE THREAD

**Issue by KarlHakanNordgren** [googleapis/java-bigquery#2765]
Hi

I'd like the result to the following query:

> SELECT * FROM `project_id`.`region-aws-us-east-1`.INFORMATION_SCHEMA.SCHEMATA
> UNION ALL
> SELECT * FROM `project_id`.`region-northamerica-northeast1`.INFORMATION_SCHEMA.SCHEMATA

The result is

> Not found: Table project_id:region-aws-us-east-1.INFORMATION_SCHEMA.SCHEMATA was not found in location northamerica-northeast1

Is it possible to do the above query in some way?

**Comment by Neenu1995** [comment]
Hi @KarlHakanNordgren ,
From what I can see, Bigquery don't allow querying multiple regions in a single command.
You could try querying it separately and appending the data together after.

For example you could use the java client library to do the following:
```
    QueryJobConfiguration asia = QueryJobConfiguration.newBuilder("SELECT * FROM `region-asia-south2`.INFORMATION_SCHEMA.SCHEMATA;").build();
    QueryJobConfiguration europe = QueryJobConfiguration.newBuilder("SELECT * FROM `region-europe-north1`.INFORMATION_SCHEMA.SCHEMATA;").build();
    TableResult asiaResult  = bigQuery.query(asia);
    TableResult europeResult = bigQuery.query(europe);
    joinBothResults(asiaResult, europeResult);

```

Hope this helps.

**Comment by KarlHakanNordgren** [comment]
@Neenu1995 : Ok thanks!
