### ISSUE TITLE
Mock Bigquery Table for Unit Testing

### ISSUE THREAD

**Issue by milley23** [googleapis/java-bigquery#2805]
Hi,

I want to mock BQ [Table](https://github.com/googleapis/java-bigquery/blob/main/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Table.java) for unit testing using Junit, because I don't want to create a real connection to BQ, but I found that all the builder constructors are private and there's no way to create Table in my unit test.

This is what I am trying to do

```
TableId TABLE_ID1 = TableId.of("dataset", "table1");
Field FIELD = Field.of("FieldName", LegacySQLTypeName.STRING);
Schema SCHEMA = Schema.of(FIELD);
TABLE_DEFINITION = StandardTableDefinition.of(SCHEMA);
Long CREATION_TIME = 10L;

Table builtTable = new Table.Builder(bigquery, TABLE_ID1, TABLE_DEFINITION).setCreationTime(CREATION_TIME).build();
```

I think, this is quite similar with [this issue](https://github.com/googleapis/java-bigquery/issues/96). 

Is it any workaround to do this ? Please help to guide me

**Comment by obada-ab** [comment]
Hello,

If you want to execute the code mentioned without creating a real connection, you can use mockito to mock the `BigQuery` class. For example, you can try:

```
BigQuery bigquery = mock(BigQuery.class);

TableId TABLE_ID1 = TableId.of("dataset", "table1");
Field FIELD = Field.of("FieldName", LegacySQLTypeName.STRING);
Schema SCHEMA = Schema.of(FIELD);
TableDefinition TABLE_DEFINITION = StandardTableDefinition.of(SCHEMA);
Long CREATION_TIME = 10L;

Table builtTable = new Table.Builder(bigquery, TABLE_ID1, TABLE_DEFINITION).setCreationTime(CREATION_TIME).build();
``` 

Let me know if you have other questions

**Comment by milley23** [comment]
Hi @obada-ab 

Thanks for your response.
I've tried using Mockito, but I got an error when trying to create the Table using Builder. 
<img width="793" alt="Screenshot 2023-07-20 at 22 43 29" src="https://github.com/googleapis/java-bigquery/assets/92920267/70d498f8-4f10-4b56-a644-ecc596e0f977">

`The constructor Table.Builder(BigQuery, TableId, TableDefinition) is not visible`

If I check [here](https://github.com/googleapis/java-bigquery/blob/main/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/Table.java), all the builders are not accesible. 

Do you have a guideline about how to create Bigquery Table using the builder, so I could define my own table schema?

**Comment by obada-ab** [comment]
Hello,

Sorry about the previous answer, `Table.Builder` should only be accessed from inside it's package.

For creating tables please refer to the [CreateTable.java](https://github.com/googleapis/java-bigquery/blob/main/samples/snippets/src/main/java/com/example/bigquery/CreateTable.java), specifically these lines:

```
BigQuery bigquery = BigQueryOptions.getDefaultInstance().getService();

TableId tableId = TableId.of(datasetName, tableName);
TableDefinition tableDefinition = StandardTableDefinition.of(schema);
TableInfo tableInfo = TableInfo.newBuilder(tableId, tableDefinition).build();

bigquery.create(tableInfo);
```

And for retrieving tables please refer to [GetTable.java](https://github.com/googleapis/java-bigquery/blob/main/samples/snippets/src/main/java/com/example/bigquery/GetTable.java):

```
TableId tableId = TableId.of(projectId, datasetName, tableName);
Table table = bigquery.getTable(tableId);
```

You can mock/stub various parts of `BigQuery.class` and `Table.class` in your unit tests, for example if you want to simulate retrieving a table without having a real connection or a real table you can do something like this:

```
BigQuery bigquery = mock(BigQuery.class);
Table mockTable = mock(Table.class);

TableId tableId = TableId.of("projectId", "datasetName", "tableName");
when(bigquery.getTable(tableId)).thenReturn(mockTable);

Table table = bigquery.getTable(tableId);
```

Let me know if you have other questions

**Comment by milley23** [comment]
Hi, 
Thanks for the guideline.

I tried to mock `BigQuery.class` and use that mock to create a table like this.
```
BigQuery bigquery = mock(BigQuery.class);

TableId TABLE_ID1 = TableId.of("project", "dataset", "table1");
Field FIELD = Field.of("FieldName", LegacySQLTypeName.STRING);
Schema SCHEMA = Schema.of(FIELD);
TableDefinition TABLE_DEFINITION = StandardTableDefinition.of(SCHEMA);

TableInfo tableInfo1 = TableInfo.newBuilder(TABLE_ID1, TABLE_DEFINITION).build();
Table table1 = bigquery.create(tableInfo1);

when(bigquery.getTable(TABLE_ID1)).thenReturn(table1);
```

But, if I run the unit test, I found that `table1` is always `null`. 
As a result, my unit test returns an error `Table not found: project.dataset.table1 `

Where did I go wrong?

**Comment by obada-ab** [comment]
you can also refer to [mockito site](https://site.mockito.org/) and the [reference documentation](https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html) for more guides and examples.

**Comment by milley23** [comment]
After this code
`Table table1 = bigquery.create(tableInfo1);`

Is it possible to `setDefinition` to `table1`, so as a final result, I have `table1` with TableDefinition in it?
so for example, when I stub this, it will return `table1` with TableDefinition information
`when(bigquery.getTable(TABLE_ID1)).thenReturn(table1);`

I've tried this, but it's not working
`table1 = table1.toBuilder().setDefinition(TABLE_DEFINITION).build().update();`

**Comment by obada-ab** [comment]
Hello,

You can check the resources above for details and guides on mocking, If you can any questions related specifically to BigQuery Java client library feel free to ask them here.
