### ISSUE TITLE
What is the relationship between the Protobuf models in bigquery.storage.v1 and JSON models in bigquery.model ?.

### ISSUE THREAD

**Issue by damnMeddlingKid** [googleapis/java-bigquery#2831]
Im currently using the JSON models for `TableFieldSchema` from `com.google.api.services.bigquery.model` , this has an equivalaent model in `com.google.cloud.bigquery.storage.v1` derived from Protobuf. What is the relationship between these two ?.

1) Can i convert to and from these models somehow ?, the protobuf has a well typed interface that is nice to work with but some utility functions expect the JSON model
2) Can i rely on these two models to be in sync with each other ?. 

For example i'd like to import constants from the proto version and use it to build the json model.

```
import com.google.api.services.bigquery.model.{TableFieldSchema => JSONTableFieldSchema} //alias import
import com.google.cloud.bigquery.storage.v1.{TableFieldSchema => ProtoTableFieldSchema} //alias import

new JSONTableFIeldSchema().setType(ProtoTableFieldSchema.Type.STRING.name()) 
```

instead of 

```
new JSONTableFIeldSchema().setType("STRING") 
```

**Comment by blakeli0** [comment]
@Neenu1995 Transferring this issue to BigQuery since it's BigQuery specific.

**Comment by PhongChuong** [comment]
Hi @damnMeddlingKid ,

Sorry for the late reply:
1. There are no helper methods to convert between the 2 format from java-bigquery and java-bigquerystorage. The one that you have found is from apache beam. We'll look into unifying the interface differences in java-bigquery and java-bigquerystorage in the future.
2. The models may not be in complete sync with each other as the 2 libraries can follow different release schedule. However, in general, they will be relatively in sync as they are both generated source.

As this question is a year old, I'm closing this issue. Feel free to open another issue if you have further questions.
