### ISSUE TITLE
BigQuery: google-cloud-bigquery 2.31.0 breaks compatibility with Kotlin 1.6 via dependency on auto-value 1.10.2

### ISSUE THREAD

**Issue by breun** [googleapis/java-bigquery#2852]
#### Environment details

* OS type and version: macOS 13.5
* Java version: 17

#### Steps to reproduce

  1. Use `com.google.cloud:google-cloud-bigquery` 2.31.0 in a Kotlin 1.6 project
  2. Project compilation fails with:
```[ERROR] /path/to/.m2/repository/com/google/auto/value/auto-value/1.10.2/auto-value-1.10.2.jar!/META-INF/kotlin-stdlib-common.kotlin_module: (-1, -1) Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.```

However, with `google-cloud-bigquery` 2.30.1 it works.

It seems this is caused by the update to auto-value 1.10.2, which [broke compatibility with Kotlin 1.6](https://github.com/google/auto/issues/1574). It looks like `auto-value` is exploring a solution that might restore compatibility with these Kotlin versions.

I encountered this issue while using Spring Cloud GCP 3.6.1 or later, because that is the first version that (transitively) includes `google-cloud-bigquery` 2.31.0. See [here](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/2122) for a bug report with a sample reproduction project that demonstrates this issue.

**Comment by Neenu1995** [comment]
Hi @breun ,
Thanks for bringing this to our attention. 

I see the auto-value team is working on it. When auto-value release a fix, the bigquery library will upgrade and release.

**Comment by Neenu1995** [comment]
@suztomo FYI

**Comment by eamonnmcmanus** [comment]
Updating to the just-released AutoValue 1.10.3 should fix this problem.

**Comment by obada-ab** [comment]
The latest release has updated dependencies and uses auto-value 1.10.4, closing this issue
