### ISSUE TITLE
Support connectionProperties for job/query insertion

### ISSUE THREAD

**Issue by shollyman** [googleapis/java-bigquery#306]
Once the discovery dependency is released at rev20200415 or later, we should include the ability to set connection properties as part of the job configuration for queries.  They're key/value pairs, defined in discovery thusly:

  "ConnectionProperty": {
      "id": "ConnectionProperty",
      "type": "object",
      "properties": {
        "value": {
          "description": "[Required] Value of the connection property.",
          "type": "string"
        },
        "key": {
          "description": "[Required] Name of the connection property to set.",
          "type": "string"
        }
      }
    },

They're available in the discovery resources JobConfigurationQuery and QueryRequest as an array:

"connectionProperties": {
          "type": "array",
          "items": {
            "$ref": "ConnectionProperty"
          },
          "description": "Connection properties."
        },

Please include the necessary functionality in the manual layer to be able to set/interact connection properties.  Will followup with more detail about available properties.

**Comment by shollyman** [comment]
https://cloud.google.com/bigquery/docs/reference/rest/v2/ConnectionProperty does indicate the current only allowed param (time_zone)

**Comment by shollyman** [comment]
Looks like the discovery artifacts made it through release end of last week: https://search.maven.org/artifact/com.google.apis/google-api-services-bigquery/v2-rev20200415-1.30.9/jar

This should be unblocked.

**Comment by stephaniewang526** [comment]
Yes - a PR will be made tomorrow.
