### ISSUE TITLE
Add pagination support for projects.list API

### ISSUE THREAD

**Issue by stephaniewang526** [googleapis/java-bigquery#310]
The underlying [projects.list API](https://cloud.google.com/bigquery/docs/reference/rest/v2/projects/list) supports pagination but not the Java client. We should add support this in the client so that customers can request next page and work with all the projects.

**Comment by shollyman** [comment]
We've historically not implemented projects.list API in the manual layer as this has been superseded by the resource manager API.

We should ensure that this is better discovered by users.  The underlying method already indicates to use resource manager and links to it: https://cloud.google.com/bigquery/docs/reference/rest/v2/projects/list

**Comment by stephaniewang526** [comment]
Got it - closing per comment above.

**Comment by matthewbluezyoncom** [comment]
I have a problem with your statement that the Resource Manager API should be used instead. 

The Resource Manager API requires `cloud-platform` or`cloud-platform.readOnly` scopes.  These are way too permissive for simply listing the projects a login has access to.

As a 3rd Party app developer it is very unlikely that a client is willing to allow access to those scopes for their login;  And as a responsible Google app developer I should not be exposing my apps to increased misuse either.

Having spent sometime looking around the Google APIs for an alternative I am yet to find one.

Any suggestions ?

**Comment by matthewbluezyoncom** [comment]
I finally managed to find a solution, Resource Manager has some other scopes I had missed:
`https://www.googleapis.com/auth/cloudplatformprojects.readonly`
`https://www.googleapis.com/auth/cloudplatformprojects`
