### ISSUE TITLE
Question: Does BigQuery java SDK support Kotlin coroutines?

### ISSUE THREAD

**Issue by therealansh** [googleapis/java-bigquery#3118]
As the title says, Does BigQuery java sdk reactively hits the query API or not. If not, is there a work around where this support can be added to fetch the data reactively using coroutines or suspend functions?

**Comment by whuffman36** [comment]
Thanks for the comment. As of now, the BigQuery java sdk does not support Kotlin routines, and as far as I know there are no plans to support that feature (they are different languages after all). There are talks regarding creating a Kotlin sdk for BigQuery, however. Unfortunately I cannot provide an estimate on when or even if the Kotlin sdk will be released. In the meantime, here are a few links that you might find useful:

[Calling Kotlin Suspend Functions from Java](https://stackoverflow.com/questions/52869672/call-kotlin-suspend-function-in-java-class)

[Coroutine Implementation in Java](https://stackoverflow.com/questions/2846664/implementing-coroutines-in-java)
