### ISSUE TITLE
BigQueryOption setHost() is broken

### ISSUE THREAD

**Issue by gilles** [googleapis/java-bigquery#3141]
```
BigQueryOptions options =
        BigQueryOptions.newBuilder().setProjectId(project).setHost("<emulator>").setLocation("<emulator>").build();
return options.getService();
```

Expected to connect to the emulator, instead it's trying to connect to default production

This is the change that broke things https://github.com/googleapis/java-bigquery/compare/v2.36.0...v2.37.0#diff-a5b2825562e3ffa23e5250337fa30f136c7ee6b3409b66f0da4fc78c8b9414d6L108

=> `ServiceOptions.getHost()` tries to look for overrides in options then default. `ServiceOptions.getResolvedApiaryHost()` does not

**Comment by PhongChuong** [comment]
Hi,
Thank you for reporting the issue.
This is a known recent bug, we're currently working a fix. Please downgrade to downgrade to 2.35.0 for now. See https://github.com/googleapis/java-bigquery/issues/3125 for more detail and status of the fix.
