### ISSUE TITLE
FieldValueList & FieldValue throwing null pointer exception when getting value of nullable field

### ISSUE THREAD

**Issue by Sam-Bate-ITV** [googleapis/java-bigquery#3179]
I have a table with numerous nullable fields but when using the Java api to get the data from a row I've found that instead of simply getting null instead of a string the code throws an exception.

https://github.com/googleapis/java-bigquery/blob/45c5096c756a6599233935553708af4f53de5d58/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/FieldValue.java#L107-L121

As users are likely to want to map all results from a query regardless of whether the field was null or not it would be better if the methods for getting a String or Long handled null gracefully. Or at least provide an alternative method where the caller can provide a default value or null if the fields value is null. 

Fortunately as I'm using Kotlin I can work around this for now with an extension function on FieldValueList:

```
fun FieldValueList.getNullable(name: String): FieldValue? = if (this.get(name).isNull) null else this.get(name)
```

which in turn means I can simply do `row.getNullable("my_nullable_column")?.stringValue` when mapping the _FieldValueList_ to an object.

If `getStringValue()` had on overloaded method that takes an arg that's used as a default I could have done something like:

```
row.get("my_nullable_column").getStringValue(null)
```

which would be convenient. Also this could be added without breaking the existing API.

**Comment by PhongChuong** [comment]
Hi @Sam-Bate-ITV ,
Would it preferable for your use case to:
1. Provide an overloaded getStringValue (from the post) or new method getStringValueOrDefault with similar behavior
2. Provide a knob to turn off the checkNotNull check

**Comment by Sam-Bate-ITV** [comment]
either would be fine for me as long as it's consistent with other methods that allow a default fallback
