### ISSUE TITLE
BigQuery API: How to get database metadata via API ?

### ISSUE THREAD

**Issue by TetianaShcherbak** [googleapis/java-bigquery#3297]
Hi team, 
There is widely used interface [DatabaseMetaData](https://docs.oracle.com/javase/8/docs/api/java/sql/DatabaseMetaData.html) which is usually implemented by driver vendors. 
And there also is JDBC driver implemented by Simba: [see google docu...](https://cloud.google.com/bigquery/docs/reference/odbc-jdbc-drivers#how_do_i_get_support_for_these_drivers) .

Simba's JDBC driver has limited capabilities in terms of performance, that's why I've decided to stick with BigQuery API. 
**How can I get DatabaseMetaData info via API?**
Or even **Is there a way to get DatabaseMetaData info via API?** 

Btw, it looks like corresponding values of DatabaseMetaData in Simba's JDBC driver are hard-coded... (if I'm mistaken, please, let me know). 

In case these data are not available via API, please, let me know if there are plans to introduce such enhancement. 

Appreciate your effort, thanks! 

PS.: as example of response Simba's driver are capable of, attaching json file. Some data there is missing, didn't want to share any vulnerable info. 
Please, advice if it's possible to get at least some of these values via API. The database version is crucial for me. 
[GoogleBigQueryDatabaseMetadataResponse_Example.json](https://github.com/googleapis/java-bigquery/files/15262718/GoogleBigQueryDatabaseMetadataResponse_Example.json)

**Comment by PhongChuong** [comment]
Hi,
[DatabaseMetaData](https://docs.oracle.com/javase/8/docs/api/java/sql/DatabaseMetaData.html) is not a feature of the BigQuery API. While it is provided in JBDC drivers, there is currently no plan to provide this feature in the BigQuery API.

**Comment by TetianaShcherbak** [comment]
Thanks for the response.
