### ISSUE TITLE
BigQuery API fails with Guava method not found on Dataproc clusters

### ISSUE THREAD

**Issue by harishreedharan** [googleapis/java-bigquery#333]
#### Environment details

1. Specify the API at the beginning of the title. For example, "BigQuery: ...").
  com.google.cloud.bigquery.BigQueryImpl
2. Environment: **Dataproc image version: 1.4-ubuntu18**
3. bigquery version(s): 1.108.1

#### Steps to reproduce
1. Run a simple java app that runs a SQL Query on **dataproc**, using the `BigQuery.query(..)` API. Since dataproc ships with a very old version of Guava (15.x I think, which presumably is hard to change due to it being shipped with Spark), a `NoSuchMethodError` gets thrown here: https://github.com/googleapis/java-bigquery/blob/master/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java#L1257

#### Code example

```scala
      val create = "CREATE TABLE a (i int, j string)"
      val createConfig = QueryJobConfiguration.newBuilder(create).build()
      bigquery.query(createConfig)
```

#### Stack trace
```
com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V
java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V
	at com.google.cloud.bigquery.BigQueryImpl.optionMap(BigQueryImpl.java:1257)
	at com.google.cloud.bigquery.BigQueryImpl.getQueryResults(BigQueryImpl.java:1185)
	at com.google.cloud.bigquery.Job$1.call(Job.java:329)
	at com.google.cloud.bigquery.Job$1.call(Job.java:326)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)
	at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
	at com.google.cloud.RetryHelper.poll(RetryHelper.java:64)
	at com.google.cloud.bigquery.Job.waitForQueryResults(Job.java:325)
	at com.google.cloud.bigquery.Job.getQueryResults(Job.java:291)
	at com.google.cloud.bigquery.BigQueryImpl.query(BigQueryImpl.java:1173)
```

To work around this issue, I am shading `com.google.guava:guava`, `com.google.cloud:google-cloud-bigquery` and `com.google.apis:google-api-services-bigquery`. Guava should either be shaded in the jar or just copy Preconditions over.

Thanks!

**Comment by pmakani** [comment]
@harishreedharan it is well known issue across multiple clients. could you please check on [TROUBLESHOOTING](https://github.com/googleapis/google-cloud-java/blob/master/TROUBLESHOOTING.md#classnotfoundexception-nosuchmethoderror-noclassdeffounderror)

**Comment by harishreedharan** [comment]
@pmakani the issue here is not anything my code ships. It is the BigQuery API that is itself incompatible with dataproc. You can reproduce this if you simply open a spark-shell with big query api passed into the coordinates. This makes BigQuery unusable via spark-shell or when I cannot shade the dependencies.
