### ISSUE TITLE
Can we get the configured time travel window for a Table

### ISSUE THREAD

**Issue by rmulton** [googleapis/java-bigquery#3538]
Hi there,

I don't seem to find a way to get the configured time travel window for a Table (mentioned in the docs here https://cloud.google.com/bigquery/docs/time-travel#configure_the_time_travel_window), is that available from the java client or the API?

I've only found TableInfo.getNumTimeTravelPhysicalBytes() https://github.com/googleapis/java-bigquery/blob/e78e78cba7769a55b3e5937cf6a5a84f5259d116/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/TableInfo.java#L555 and TableInfo.getCreationTime()

Thanks!
Robin

**Comment by whuffman36** [comment]
Hi Robin

Thanks for bringing this to our attention. We just introduced the capability of checking the time travel window from the java client library. The time travel window is a dataset level attribute, and all tables within a dataset will have the same time travel window. To get the time travel window for a dataset, you can use the new method [Dataset.getMaxTimeTravelHours()](https://github.com/googleapis/java-bigquery/blob/main/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/DatasetInfo.java#L553). Hope this helps!
