### ISSUE TITLE
How can I perform bigquery.tabledata().insertAll using the Cloud Bigquery API

### ISSUE THREAD

**Issue by shrgupta28** [googleapis/java-bigquery#429]
Hi Team,

@danoscarmike @stephaniewang526 @pmakani 

I need help on an urgent basis.

As per your recommendation, we are migrating to the new Bigquery API https://github.com/googleapis/java-bigquery

Can you please help me how I can perform `bigquery.tabledata().insertAll` using the Cloud Bigquery API

Earlier we were using BigQuery V2 API to achieve this functionality.

Env:
Java 1.8
Google Cloud Bigquery

Thanks,
Shruti

**Comment by pmakani** [comment]
@shrgupta28 you can use this example for insert data. [InsertDataAndQueryTable](https://github.com/googleapis/google-cloud-java/blob/master/google-cloud-examples/src/main/java/com/google/cloud/examples/bigquery/snippets/InsertDataAndQueryTable.java#L47-L87)

**Comment by shrgupta28** [comment]
Okay.. thanks for your response.

**Comment by pmakani** [comment]
@shrgupta28 there is alternative way to use getInsertErrors() , which returns number of rows were not inserted.

**Comment by shrgupta28** [comment]
Okay, thanks for this information.
I am requesting similar information for https://github.com/googleapis/java-bigquery/issues/413

**Comment by pmakani** [comment]
@shrgupta28 second approach is insert data through `LoadJobConfiguration` and Load Job example available in samples, once you execute load job , it will return `LoadStatistics`, please check below code.
```JAVA
LoadStatistics statistics = job.getStatistics();
long outputRows = statistics.getOutputRows();
```
