### ISSUE TITLE
Allow setting scopes to access datasets backed by Google Sheets

### ISSUE THREAD

**Issue by neoeinstein** [googleapis/java-bigquery#53]
**Is your feature request related to a problem? Please describe.**
When using the tool StreamSets, we receive authorization errors when attempting to access a table in a dataset which is backed by a Google Sheets document in Google Drive. The authorization error indicates that the Google Drive scope was not requested, and that seems to not be something that can be added based on the [`BigQueryOptions` code][1]. The target sheet has been shared with the service account user, but without the requested scope, we are unable to programatically access the data.

[1]: https://github.com/googleapis/java-bigquery/blob/master/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryOptions.java#L34

**Describe the solution you'd like**
Ability to request additional scopes when building `BigQueryOptions`.

**Additional context**
Error text in StreamSets:

```
com.streamsets.pipeline.api.StageException: BIGQUERY_02 - Query Job execution error: 'BigQueryError{reason=invalid, location=1vvgwO1QfOdP0RODhx9li5pgHKTGtGVzFdXqiZbiTJLk, message=Error while reading table: sheets_integration.page_cat_clean, error message: Failed to read the spreadsheet. Errors: No OAuth token with Google Drive scope was found.}
```

![image](https://user-images.githubusercontent.com/18165/71267528-c6387f00-2318-11ea-90bd-a7d8b8ac66f5.png)

**Comment by stephaniewang526** [comment]
Hi, thank you for your question. 

In other languages, we handle this by showing an example of explicitly creating credentials with those scopes - https://cloud.google.com/bigquery/external-data-drive. We will be adding the Java sample soon. I imagine this can be done with the auth library. Please give it a go. 

Cheers,
Stephanie
