### ISSUE TITLE
Does Google Cloud BigQuery Client for Java Supports OpenJDK?

### ISSUE THREAD

**Issue by shrgupta28** [googleapis/java-bigquery#551]
Hi Team,

We wanted to check if https://github.com/googleapis/java-bigquery supports Open JDK?

Can you please confirm this?

Thanks,
Shruti Gupta

**Comment by pmakani** [comment]
@shrgupta28 yes it's supports both Open JDK and Oracle JDK.

**Comment by shrgupta28** [comment]
@pmakani Thanks for the quick response. Can you share the quick documentation for Open JDK?

**Comment by stephaniewang526** [comment]
https://cloud.google.com/java/docs/setup
