### ISSUE TITLE
String value t and f converted to true/false in TableDataWriteChannel

### ISSUE THREAD

**Issue by vadimatscale** [googleapis/java-bigquery#650]
#### Environment details

1. BigQuery
2. OS type and version: OSX and also Amazon Linux
3. Java version: 8
4. google-cloud-java version(s): 1.116.8

#### Steps to reproduce

  1.  Create a json file with simple entries like so
{"projectname":"t","projectID":"03c096d5-88b3-4c6f-50b5-dca5c414da2b"}
{"projectname":"f","projectID":"03c096d5-88b3-4c6f-50b5-dca5c414da2b"}

  2. Create a table in BigQuery with 2 fields, 
projectID | STRING | NULLABLE |   |  
projectname | STRING | NULLABLE

3. In Java code, configure Channel writer as follows (with setAutodetect=true).

```
WriteChannelConfiguration writeChannelConfiguration = WriteChannelConfiguration.newBuilder(tableId)
              .setFormatOptions(FormatOptions.json()).setAutodetect(true).setWriteDisposition(wd).setIgnoreUnknownValues(true).build();
```
4. Once the data loads, the table schema changes in BigQuery, with projectname becoming BOOLEAN with values true/false instead of staying string "t"/"f" respectfully.
projectID | STRING | NULLABLE |   |  
projectname | BOOLEAN | NULLABLE

#### Code example

```java

File credentialsPath = new File("{your-service-account-json}");
        FileInputStream serviceAccountStream = new FileInputStream(credentialsPath);

        GoogleCredentials credentials = ServiceAccountCredentials.fromStream(serviceAccountStream);
        private static BigQuery bigquery = BigQueryOptions.newBuilder().setCredentials(credentials).build().getService();

long startTimeLoad = System.nanoTime();

        TableId tableId = TableId.of(datasetname, tableName);

WriteChannelConfiguration writeChannelConfiguration = WriteChannelConfiguration.newBuilder(tableId)
              .setFormatOptions(FormatOptions.json()).setAutodetect(true).setWriteDisposition(WriteDisposition.WRITE_TRUNCATE ).setIgnoreUnknownValues(true).build();

JobId jobId = JobId.newBuilder().setLocation(location).build();
        TableDataWriteChannel writer = bigquery.writer(jobId, writeChannelConfiguration);

        // Write data to writer
        try (OutputStream outputStream = Channels.newOutputStream(writer)) {
            Files.copy(path, outputStream);
        }

        // Get load job
        Job job = writer.getJob();
        job = job.waitFor();
        LoadStatistics stats = job.getStatistics();
```

**Comment by pmakani** [comment]
@vadimatscale I am able to import json file with exact data types, which are in json file but i have made little bit changes. first you do not need to create table, second you need to pass that schema in `WriteChannelConfiguration`. you could check below example code as well.

```JAVA
    Field projectId = Field.of("projectID", StandardSQLTypeName.STRING);
    Field projectName = Field.of("projectname", StandardSQLTypeName.STRING);
    Schema schema = Schema.of(projectId, projectName);
    WriteChannelConfiguration channelConfig =
        WriteChannelConfiguration.newBuilder(TableId.of(datasetId, tableId))
            .setSchema(schema)
            .setFormatOptions(FormatOptions.json())
            .setAutodetect(true)
            .setWriteDisposition(JobInfo.WriteDisposition.WRITE_APPEND)
            .setIgnoreUnknownValues(true)
            .build();
```

**Comment by vadimatscale** [comment]
@pmakani thanks for the info and I'll use that as a workaround for the time being, however that still doesn't address the issue of automatically changing values t and f to true and false Boolean instead of keeping them as strings.

Thanks

**Comment by vadimatscale** [comment]
@stephaniewang526 Can you review my last comment please? This is still a bug in my opinion.

**Comment by stephaniewang526** [comment]
Checking with backend team on this issue.

**Comment by shollyman** [comment]
As has been previously discussed, schema autodetection is the problematic aspect here.  If your values had diversity beyond just t and f, this should not get treated as a boolean data column.

Your options are:
1) disable autodetect, provide an explicit schema to the load job (pkmakan's example)
2) Instead use a format like avro, which embeds the schema alongside the serialized data records.
3) Coerce this back to the intended values at query time using an conditional construct like an IF or CASE statement. e.g. `IF(project IS NULL,NULL,IF(project,'t','f'))`

If you'd like to recommend changes to the autodetect mechanism, the best place to surface them is via the [public issue tracker](https://issuetracker.google.com/issues/new?component=187149&template=0).  This repository is specifically for tracking issues related to the java client library, which has no ability to alter this behavior.
