### ISSUE TITLE
Reformat plugin is misbehaving with spaces

### ISSUE THREAD

**Issue by elharo** [googleapis/java-bigquery#72]
The autoformat plugin is formatting code like this:

```
    expect(
            bigqueryRpcMock.open(
                new com.google.api.services.bigquery.model.Job()
                    .setJobReference(JOB_INFO.getJobId().toPb())
                    .setConfiguration(LOAD_CONFIGURATION.toPb())))
        .andThrow(ex);
```

That is, it is indenting code eight spaces on continuation lines, possibly in concert with Eclipse. I'm not sure why.

**Comment by stephaniewang526** [comment]
Issue raised in google-java-format: https://github.com/google/google-java-format/issues/430.

**Comment by stephaniewang526** [comment]
As noted in ticket raised -- this is expected formatting behavior. https://github.com/google/google-java-format/wiki/FAQ#google-java-format-always-follows-the-rectangle-rule-right-no-exceptions
