### ISSUE TITLE
Pagination for views

### ISSUE THREAD

**Issue by darkmakukudo** [googleapis/java-bigquery#828]
Tried to do pagination targeting big query views but not able to make it work. Is pagination for views supported?

**Comment by pmakani** [comment]
@cariquitanmac Yes list of views is not supported but you can use listTables which returns views as well.

**Comment by cariquitanmac** [comment]
@pmakani  do we a code sample for that? can't find any from documentation

**Comment by pmakani** [comment]
@cariquitanmac you can use below example 

```JAVA
    Page<Table> tables = bigquery.listTables(DATASET);
    for (Table table : tables.iterateAll()) {
      if (table.getDefinition().getType().name() == "VIEW") {
        System.out.println(table);
      }
    }
```

**Comment by cariquitanmac** [comment]
Thanks but I'm looking to paginate the result of views sort of the same as presented in this documentation:
https://cloud.google.com/bigquery/docs/paging-results#bigquery_browse_table-java

**Comment by pmakani** [comment]
@darkmakukudo please check below example.

```JAVA
public class ViewExample {

  public static void main(String[] args) throws InterruptedException {
    BigQuery bigquery = BigQueryOptions.getDefaultInstance().getService();
    String datasetName = "your-dataset-name";
    String tableName = "your-table-name";
    String viewName = "your-view-name";

    String query =
        String.format(
            "SELECT field1, field2 FROM %s.%s", datasetName, tableName);

    // Create a view
    TableId viewId = TableId.of(datasetName, viewName);

    ViewDefinition viewDefinition = ViewDefinition.newBuilder(query).setUseLegacySql(false).build();
    bigquery.create(TableInfo.of(viewId, viewDefinition));

    // Query on view
    String viewQuery = String.format("SELECT * FROM %s.%s", datasetName, viewName);
    Job queryJob = bigquery.create(JobInfo.of(QueryJobConfiguration.of(viewQuery)));
    TableResult results = queryJob.getQueryResults(BigQuery.QueryResultsOption.pageSize(1000));
    results
        .iterateAll()
        .forEach(row -> row.forEach(val -> System.out.printf("%s\n", val.toString())));
  }
}
```

**Comment by darkmakukudo** [comment]
Great work! Tested it working thank you.
For others that needs documentation, here are the links:

[TableResult](https://googleapis.dev/java/google-cloud-bigquery/latest/com/google/cloud/bigquery/TableResult.html)
[QueryResultsOption](https://googleapis.dev/java/google-cloud-clients/0.89.0-alpha/com/google/cloud/bigquery/class-use/BigQuery.QueryResultsOption.html)
