### ISSUE TITLE
variable name instead of the value in dashboard

### ISSUE THREAD

**Issue by elharo** [googleapis/java-bigquery#908]
Not sure if this is an issue in this project or the dashboard code but on

https://storage.googleapis.com/java-cloud-bom-dashboard/com.google.cloud/google-cloud-bom/0.141.0/index.html

I saw this:

![image](https://user-images.githubusercontent.com/1005544/97992050-16f28280-1dda-11eb-94d9-e5133fc89975.png)

note how we get the variable name instead of the value

**Comment by stephaniewang526** [comment]
Thanks for reporting the bug @elharo -- an existing issue captures this https://github.com/googleapis/java-bigquery/issues/881.
We will keep track of the work in the exiting ticket.
