### ISSUE TITLE
docs(samples): create a new sample to show running the same query in multiple threads using custom http transport

### ISSUE THREAD

**Issue by stephaniewang526** [googleapis/java-bigquery#932]
Investigate and find out how a user could run multiple queries concurrently using the BQ Java client library.
![Screen Shot 2020-11-19 at 10 51 22 AM](https://user-images.githubusercontent.com/7338432/99689917-8b255b00-2a55-11eb-8e6d-9933be08bff9.png)

**Comment by cvonredapt** [comment]
The client is wondering why this conversation was closed. The question is still unanswered. Did we miss a request for additional information?
