### ISSUE TITLE
Mocking Bigquery Dataset

### ISSUE THREAD

**Issue by mauliksoneji** [googleapis/java-bigquery#96]
I have the following piece of code where I am first checking if the dataset exists or not and if the dataset doesn't exist, I create the dataset.

`        
if (!bigquery.getDataset(tableID.getDataset()).exists()) {
            bigquery.create(DatasetInfo.of(tableID.getDataset()));
        }
`

I am having difficulty in mocking the call `bigquery.getDataset(tableID.getDataset())`. 
I am currently using Junit 4 and I am not able to mock the call.

If I do
`
when(bigquery.getDataset(tableId.getDataset())).thenReturn(new Dataset.Builder(bigquery, tableId.getDataset()));
`
then there is no way to create a Dataset in test. The Builder constructors are not public and we cannot build Dataset from DatasetInfo.

In this case, we cannot directly mock the call to getDataset.

Please guide as to how we can mock the call to getDataset.

**Comment by stephaniewang526** [comment]
Hi,
Could you try:
` BigQuery bigquery = BigQueryOptions.getDefaultInstance().getService();
      DatasetId datasetId = DatasetId.of(projectId, datasetName);
      Dataset dataset = bigquery.getDataset(datasetId);`

Please find the sample I wrote recently here for full detail: https://github.com/googleapis/java-bigquery/blob/e7c44b4ba496d026ab182fb2d090afa6d953f891/samples/src/main/java/com/example/bigquery/GetDatasetInfo.java#L39

Let me know if you still have questions. Thanks!

**Comment by stephaniewang526** [comment]
closing due to no follow-up.
